### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by wtip** [jmaxxz/particle-smartthings#1]
I just tried installed the smart app and generic device handler but get an error when I try to open the smart app through the smartthings android app. Is the current code in working order?

**Comment by jmaxxz** [comment]
Yes it is. Which smart things app are you using? The new one or the old one?

**Comment by wtip** [comment]
I am using the old smartthings classic app

**Comment by rdmorin** [comment]
I am also not able to use this. The smartapp installs but does not open when I tap it in the old SmartThings app.

**Comment by jmaxxz** [comment]
I will provide better directions soon

**Comment by jmaxxz** [comment]
You need to set an appSetting named "particleToken" containing a particle api token. I should really have made this part of the install process. Will patch that in. Thanks for reporting.

You can set this value in the ide to get it working today.

**Comment by rdmorin** [comment]
That makes sense. I felt like I was missing where the authentication information/token was input. Thanks for your response!

**Comment by jmaxxz** [comment]
Just pushed an update which should make this easier. The api token can now be set during app install. After updating to the new version you will need to view and save the smartapp settings (on phone).
